import Head from 'next/head';
import { React, useEffect, useState } from 'react';
import axios from 'axios';
import { Mynavbar } from './components/Mynavbar.component';
import MyTable from './components/MyTable';

export default function Home() {
  const [products, setProducts] = useState([]);

  // get all products
  const getProducts = () => {
    axios.get('http://localhost:4001/api/getproducts').then((res) => {
      setProducts(res.data);
    });
  };

  useEffect(() => {
    getProducts();
  }, []);

  return (
    <div>
      <Head>
        <title>Inventory Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/truck.png" />
      </Head>

      <Mynavbar />
      <main className="mx-5 my-5">
        <h3>Products Inventory</h3>
        <MyTable products={products} />
      </main>

    </div>
  );
}
