import Head from 'next/head';
import {
  React, useEffect, useState,
} from 'react';
import axios from 'axios';
import MyNavBar from './components/MyNavBar.component';
import MyTable from './components/MyTable.component';
import AddProduct from './components/AddProduct.component';
import Download from './components/Download.component';

export default function Home() {
  const [products, setProducts] = useState([]);

  // get all products
  const getProducts = () => {
    axios.get('http://localhost:4001/api/getproducts').then((res) => {
      setProducts(res.data);
    });
  };

  useEffect(() => {
    getProducts();
  }, []);

  return (
    <div>
      <Head>
        <title>Inventory Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/truck.png" />
      </Head>

      <MyNavBar />
      <main className="mx-5 my-5">
        <div className="mx-5">
          <h3>Products</h3>
          <MyTable products={products} getProducts={getProducts} />
          <br />
          <AddProduct getProducts={getProducts} />
          <br />
          <br />
          <Download />

        </div>
      </main>

    </div>
  );
}
